version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DATABASE_NAME: "${DATABASE_NAME}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DATABASE_HOST: db
      DATABASE_PORT: "${DATABASE_PORT}"
    command: sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
 
volumes:
  pgdata:
  app: